# Enable or UnEnable (true or false) and messages
#settings
join-quit-message:
  enabled: true
  join-message: "%player_name% has joined"
  leave-message: "%player_name% has left"

chat-message:
  enabled: true
  player-chat: "%vault_prefix% %player_name% > %message%"

# messages of commands
# fly
only-players: "&cThis command can only be executed by a player."
no-permission: "&cYou do not have permission to fly."
invalid-player: "&cThis player does not exist."
flying-enabled: "&a%player_name% can now fly."
flying-disabled: "&c%player_name% can no longer fly."
# ping
ping-message: "Your ping is %player_colored_ping% ms."
# invsee
player-not-online: "&cThis player is not online."
# ipweather
ipweather-off: "Rain and snow are now disabled."
ipweather-on: "Rain and snow are now enabled."
# skull
own-head: "You received your own head!"
error-head: "Error creating the head!"
invalid-skull-use: "Incorrect usage of the command! Use /skull for your own head or /skull {player} for the head of a specified player."

# modinfo for moderator
modinfo:
  - "&l=====%player_name%====="
  - "Information&4 >&r"
  - "Username&4 >&r %player_name%"
  - "Premium&4 >&r %premium%"
  - "Rank&4 >&r %vault_prefix%"
  - "IP&4 >&r %player_ip%"
  - "UUID &4>&r %player_uuid%"
  - "Last Connection&4 >&r %player_last_join_date%"
  - "First Connection&4 >&r %player_first_join_date%"
  - "Connected&4 >&r %player_online%"
  - "&l=====%player_name%====="
